spring.application.name=pos-change-api
spring.main.allow-bean-definition-overriding=true
server.port=8081
debug=false


# Spring DataSource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/main?serverTimezone=Asia/Taipei&characterEncoding=utf-8}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# Spring Jackson Configuration
spring.jackson.time-zone=GMT+8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# MyBatis Configuration
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.alin.lin.dto,com.alin.lin.entity
mybatis.configuration.map-underscore-to-camel-case=true

# Logging Configuration
logging.level.org.mybatis=info
logging.level.com.alin.lin.mapper=info
logging.level.java.sql=info
logging.level.java.sql.Connection=info
logging.level.java.sql.Statement=info
logging.level.java.sql.PreparedStatement=info
