CREATE DATABASE IF NOT EXISTS `main`
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE `main`;

CREATE TABLE IF NOT EXISTS main_policy_master (
    policy_no VARCHAR(10) NOT NULL,
    policy_seq INT(3) NOT NULL,
    main_product_code VARCHAR(4) NOT NULL,
    main_policy_years INT(2) NOT NULL,
    insured_amount DECIMAL(10, 2) NOT NULL,
    premium DECIMAL(17, 4) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (policy_no, policy_seq)
);

CREATE TABLE IF NOT EXISTS main_policy_address (
    policy_no VARCHAR(10) NOT NULL,
    policy_seq INT(3) NOT NULL,
    address_type VARCHAR(2) NOT NULL,
    zip_code3 VARCHAR(3),
    zip_code2 VARCHAR(3),
    full_width_address VARCHAR(255),
    half_width_address VARCHAR(255),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (policy_no, policy_seq, address_type),
    CONSTRAINT fk_policy_address_master
        FOREIGN KEY (policy_no, policy_seq)
        REFERENCES main_policy_master (policy_no, policy_seq)
);

CREATE TABLE IF NOT EXISTS main_policy_ride (
    policy_no VARCHAR(10) NOT NULL,
    policy_seq INT(3) NOT NULL,
    ride_type VARCHAR(1) NOT NULL,
    ride_order VARCHAR(3) NOT NULL,
    product_code VARCHAR(4) NOT NULL,
    policy_years INT(2) NOT NULL,
    insured_amount DECIMAL(10, 2) NOT NULL,
    premium DECIMAL(17, 4) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (policy_no, policy_seq, ride_order),
    CONSTRAINT fk_policy_ride_master
        FOREIGN KEY (policy_no, policy_seq)
        REFERENCES main_policy_master (policy_no, policy_seq)
);

CREATE TABLE IF NOT EXISTS policy_change_acceptance (
    policy_no VARCHAR(10) NOT NULL,
    policy_seq INT(3) NOT NULL,
    change_case_no VARCHAR(20) NOT NULL,
    acceptance_status VARCHAR(1) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (policy_no, policy_seq, change_case_no),
    CONSTRAINT fk_change_acceptance_master
        FOREIGN KEY (policy_no, policy_seq)
        REFERENCES main_policy_master (policy_no, policy_seq)
);

CREATE TABLE IF NOT EXISTS policy_change_item (
    policy_no VARCHAR(10) NOT NULL,
    policy_seq INT(3) NOT NULL,
    change_case_no VARCHAR(20) NOT NULL,
    change_item VARCHAR(3) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (policy_no, policy_seq, change_case_no, change_item),
    CONSTRAINT fk_change_item_acceptance
        FOREIGN KEY (policy_no, policy_seq, change_case_no)
        REFERENCES policy_change_acceptance (policy_no, policy_seq, change_case_no)
);

CREATE TABLE IF NOT EXISTS policy_change_field (
    id BIGINT NOT NULL AUTO_INCREMENT,
    policy_no VARCHAR(10) NOT NULL,
    policy_seq INT(3) NOT NULL,
    change_case_no VARCHAR(20) NOT NULL,
    change_item VARCHAR(3) NOT NULL,
    change_field VARCHAR(64) NOT NULL,
    change_key VARCHAR(128),
    content_before TEXT,
    content_after TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_change_field_item
        FOREIGN KEY (policy_no, policy_seq, change_case_no, change_item)
        REFERENCES policy_change_item (policy_no, policy_seq, change_case_no, change_item)
);

CREATE TABLE IF NOT EXISTS policy_change_file (
    id BIGINT NOT NULL AUTO_INCREMENT,
    policy_no VARCHAR(10) NOT NULL,
    policy_seq INT(3) NOT NULL,
    change_case_no VARCHAR(20) NOT NULL,
    change_item VARCHAR(3) NOT NULL,
    change_file VARCHAR(64) NOT NULL,
    content_before TEXT,
    content_after TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_change_file_item
        FOREIGN KEY (policy_no, policy_seq, change_case_no, change_item)
        REFERENCES policy_change_item (policy_no, policy_seq, change_case_no, change_item)
);

ALTER TABLE main_policy_address MODIFY zip_code2 VARCHAR(3);

CREATE TABLE IF NOT EXISTS code_description (
    code_group VARCHAR(64) NOT NULL,
    code_field VARCHAR(64) NOT NULL,
    code_before VARCHAR(64) NOT NULL,
    code_after VARCHAR(64),
    code_description VARCHAR(255) NOT NULL,
    PRIMARY KEY (code_group, code_field, code_before)
);

INSERT INTO code_description (code_group, code_field, code_before, code_after, code_description)
VALUES
    ('main-policy-address', 'address_type', '01', NULL, '通訊地址'),
    ('main-policy-address', 'address_type', '02', NULL, '戶籍地址'),
    ('main-policy-address', 'address_type', '11', NULL, '通訊電話'),
    ('main-policy-address', 'address_type', '12', NULL, '戶籍電話'),
    ('main-policy-address', 'address_type', '31', NULL, 'email'),
    ('main-policy-ride', 'ride_type', '1', NULL, '主約'),
    ('main-policy-ride', 'ride_type', '2', NULL, '本人附約'),
    ('main-policy-ride', 'ride_type', '3', NULL, '眷屬附約'),
    ('policy-change-acceptance', 'acceptance_status', 'P', NULL, '受理中'),
    ('policy-change-acceptance', 'acceptance_status', 'A', NULL, '處理中'),
    ('policy-change-acceptance', 'acceptance_status', 'S', NULL, '完成'),
    ('policy-change-acceptance', 'acceptance_status', 'C', NULL, '取消'),
    ('policy-change-item', 'change_item', '001', NULL, '地址變更'),
    ('policy-change-item', 'change_item', '002', NULL, '主保額變更'),
    ('policy-change-item', 'change_item', '003', NULL, '附約保額變更')
ON DUPLICATE KEY UPDATE
    code_after = VALUES(code_after),
    code_description = VALUES(code_description);

INSERT INTO code_description (code_group, code_field, code_before, code_after, code_description)
VALUES
    ('postal-code', 'zip_code3', '100', '臺北市|中正區', 'Zhongzheng Dist., Taipei City'),
    ('postal-code', 'zip_code3', '103', '臺北市|大同區', 'Datong Dist., Taipei City'),
    ('postal-code', 'zip_code3', '104', '臺北市|中山區', 'Zhongshan Dist., Taipei City'),
    ('postal-code', 'zip_code3', '105', '臺北市|松山區', 'Songshan Dist., Taipei City'),
    ('postal-code', 'zip_code3', '106', '臺北市|大安區', 'Daan Dist., Taipei City'),
    ('postal-code', 'zip_code3', '108', '臺北市|萬華區', 'Wanhua Dist., Taipei City'),
    ('postal-code', 'zip_code3', '110', '臺北市|信義區', 'Xinyi Dist., Taipei City'),
    ('postal-code', 'zip_code3', '111', '臺北市|士林區', 'Shilin Dist., Taipei City'),
    ('postal-code', 'zip_code3', '112', '臺北市|北投區', 'Beitou Dist., Taipei City'),
    ('postal-code', 'zip_code3', '114', '臺北市|內湖區', 'Neihu Dist., Taipei City'),
    ('postal-code', 'zip_code3', '115', '臺北市|南港區', 'Nangang Dist., Taipei City'),
    ('postal-code', 'zip_code3', '116', '臺北市|文山區', 'Wenshan Dist., Taipei City'),
    ('postal-code', 'zip_code3', '200', '基隆市|仁愛區', 'Renai Dist., Keelung City'),
    ('postal-code', 'zip_code3', '201', '基隆市|信義區', 'Xinyi Dist., Keelung City'),
    ('postal-code', 'zip_code3', '202', '基隆市|中正區', 'Zhongzheng Dist., Keelung City'),
    ('postal-code', 'zip_code3', '203', '基隆市|中山區', 'Zhongshan Dist., Keelung City'),
    ('postal-code', 'zip_code3', '204', '基隆市|安樂區', 'Anle Dist., Keelung City'),
    ('postal-code', 'zip_code3', '205', '基隆市|暖暖區', 'Nuannuan Dist., Keelung City'),
    ('postal-code', 'zip_code3', '206', '基隆市|七堵區', 'Qidu Dist., Keelung City'),
    ('postal-code', 'zip_code3', '207', '新北市|萬里區', 'Wanli Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '208', '新北市|金山區', 'Jinshan Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '209', '連江縣|南竿鄉', 'Nangan Township, Lienchiang County'),
    ('postal-code', 'zip_code3', '210', '連江縣|北竿鄉', 'Beigan Township, Lienchiang County'),
    ('postal-code', 'zip_code3', '211', '連江縣|莒光鄉', 'Juguang Township, Lienchiang County'),
    ('postal-code', 'zip_code3', '212', '連江縣|東引鄉', 'Dongyin Township, Lienchiang County'),
    ('postal-code', 'zip_code3', '220', '新北市|板橋區', 'Banqiao Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '221', '新北市|汐止區', 'Xizhi Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '222', '新北市|深坑區', 'Shenkeng Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '223', '新北市|石碇區', 'Shiding Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '224', '新北市|瑞芳區', 'Ruifang Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '226', '新北市|平溪區', 'Pingxi Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '227', '新北市|雙溪區', 'Shuangxi Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '228', '新北市|貢寮區', 'Gongliao Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '231', '新北市|新店區', 'Xindian Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '232', '新北市|坪林區', 'Pinglin Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '233', '新北市|烏來區', 'Wulai Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '234', '新北市|永和區', 'Yonghe Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '235', '新北市|中和區', 'Zhonghe Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '236', '新北市|土城區', 'Tucheng Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '237', '新北市|三峽區', 'Sanxia Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '238', '新北市|樹林區', 'Shulin Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '239', '新北市|鶯歌區', 'Yingge Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '241', '新北市|三重區', 'Sanzhong Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '242', '新北市|新莊區', 'Xinzhuang Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '243', '新北市|泰山區', 'Taishan Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '244', '新北市|林口區', 'Linkou Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '247', '新北市|蘆洲區', 'Luzhou Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '248', '新北市|五股區', 'Wugu Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '249', '新北市|八里區', 'Bali Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '251', '新北市|淡水區', 'Danshui Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '252', '新北市|三芝區', 'Sanzhi Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '253', '新北市|石門區', 'Shimen Dist., New Taipei City'),
    ('postal-code', 'zip_code3', '260', '宜蘭縣|宜蘭市', 'Yilan City, Yilan County'),
    ('postal-code', 'zip_code3', '261', '宜蘭縣|頭城鎮', 'Toucheng Township, Yilan County'),
    ('postal-code', 'zip_code3', '262', '宜蘭縣|礁溪鄉', 'Jiaoxi Township, Yilan County'),
    ('postal-code', 'zip_code3', '263', '宜蘭縣|壯圍鄉', 'Zhuangwei Township, Yilan County'),
    ('postal-code', 'zip_code3', '264', '宜蘭縣|員山鄉', 'Yuanshan Township, Yilan County'),
    ('postal-code', 'zip_code3', '265', '宜蘭縣|羅東鎮', 'Luodong Township, Yilan County'),
    ('postal-code', 'zip_code3', '266', '宜蘭縣|三星鄉', 'Sanxing Township, Yilan County'),
    ('postal-code', 'zip_code3', '267', '宜蘭縣|大同鄉', 'Datong Township, Yilan County'),
    ('postal-code', 'zip_code3', '268', '宜蘭縣|五結鄉', 'Wujie Township, Yilan County'),
    ('postal-code', 'zip_code3', '269', '宜蘭縣|冬山鄉', 'Dongshan Township, Yilan County'),
    ('postal-code', 'zip_code3', '270', '宜蘭縣|蘇澳鎮', 'Suao Township, Yilan County'),
    ('postal-code', 'zip_code3', '272', '宜蘭縣|南澳鄉', 'Nanao Township, Yilan County'),
    ('postal-code', 'zip_code3', '290', '宜蘭縣|釣魚臺列嶼', 'Tiaoyutai Islands, Yilan County'),
    ('postal-code', 'zip_code3', '300', '新竹市|新竹市', 'Hsinchu City'),
    ('postal-code', 'zip_code3', '302', '新竹縣|竹北市', 'Zhubei City, Hsinchu County'),
    ('postal-code', 'zip_code3', '303', '新竹縣|湖口鄉', 'Hukou Township, Hsinchu County'),
    ('postal-code', 'zip_code3', '304', '新竹縣|新豐鄉', 'Xinfeng Township, Hsinchu County'),
    ('postal-code', 'zip_code3', '305', '新竹縣|新埔鎮', 'Xinbu Township, Hsinchu County'),
    ('postal-code', 'zip_code3', '306', '新竹縣|關西鎮', 'Guanxi Township, Hsinchu County'),
    ('postal-code', 'zip_code3', '307', '新竹縣|芎林鄉', 'Xionglin Township, Hsinchu County'),
    ('postal-code', 'zip_code3', '308', '新竹縣|寶山鄉', 'Baoshan Township, Hsinchu County'),
    ('postal-code', 'zip_code3', '310', '新竹縣|竹東鎮', 'Zhudong Township, Hsinchu County'),
    ('postal-code', 'zip_code3', '311', '新竹縣|五峰鄉', 'Wufeng Township, Hsinchu County'),
    ('postal-code', 'zip_code3', '312', '新竹縣|橫山鄉', 'Hengshan Township, Hsinchu County'),
    ('postal-code', 'zip_code3', '313', '新竹縣|尖石鄉', 'Jianshi Township, Hsinchu County'),
    ('postal-code', 'zip_code3', '314', '新竹縣|北埔鄉', 'Beibu Township, Hsinchu County'),
    ('postal-code', 'zip_code3', '315', '新竹縣|峨眉鄉', 'Emei Township, Hsinchu County'),
    ('postal-code', 'zip_code3', '320', '桃園市|中壢區', 'Zhongli Dist., Taoyuan City'),
    ('postal-code', 'zip_code3', '324', '桃園市|平鎮區', 'Pingzhen Dist., Taoyuan City'),
    ('postal-code', 'zip_code3', '325', '桃園市|龍潭區', 'Longtan Dist., Taoyuan City'),
    ('postal-code', 'zip_code3', '326', '桃園市|楊梅區', 'Yangmei Dist., Taoyuan City'),
    ('postal-code', 'zip_code3', '327', '桃園市|新屋區', 'Xinwu Dist., Taoyuan City'),
    ('postal-code', 'zip_code3', '328', '桃園市|觀音區', 'Guanyin Dist., Taoyuan City'),
    ('postal-code', 'zip_code3', '330', '桃園市|桃園區', 'Taoyuan Dist., Taoyuan City'),
    ('postal-code', 'zip_code3', '333', '桃園市|龜山區', 'Guishan Dist., Taoyuan City'),
    ('postal-code', 'zip_code3', '334', '桃園市|八德區', 'Bade Dist., Taoyuan City'),
    ('postal-code', 'zip_code3', '335', '桃園市|大溪區', 'Daxi Dist., Taoyuan City'),
    ('postal-code', 'zip_code3', '336', '桃園市|復興區', 'Fuxing Dist., Taoyuan City'),
    ('postal-code', 'zip_code3', '337', '桃園市|大園區', 'Dayuan Dist., Taoyuan City'),
    ('postal-code', 'zip_code3', '338', '桃園市|蘆竹區', 'Luzhu Dist., Taoyuan City'),
    ('postal-code', 'zip_code3', '350', '苗栗縣|竹南鎮', 'Zhunan Township, Miaoli County'),
    ('postal-code', 'zip_code3', '351', '苗栗縣|頭份市', 'Toufen City, Miaoli County'),
    ('postal-code', 'zip_code3', '352', '苗栗縣|三灣鄉', 'Sanwan Township, Miaoli County'),
    ('postal-code', 'zip_code3', '353', '苗栗縣|南庄鄉', 'Nanzhuang Township, Miaoli County'),
    ('postal-code', 'zip_code3', '354', '苗栗縣|獅潭鄉', 'Shitan Township, Miaoli County'),
    ('postal-code', 'zip_code3', '356', '苗栗縣|後龍鎮', 'Houlong Township, Miaoli County'),
    ('postal-code', 'zip_code3', '357', '苗栗縣|通霄鎮', 'Tongxiao Township, Miaoli County'),
    ('postal-code', 'zip_code3', '358', '苗栗縣|苑裡鎮', 'Yuanli Township, Miaoli County'),
    ('postal-code', 'zip_code3', '360', '苗栗縣|苗栗市', 'Miaoli City, Miaoli County'),
    ('postal-code', 'zip_code3', '361', '苗栗縣|造橋鄉', 'Zaoqiao Township, Miaoli County'),
    ('postal-code', 'zip_code3', '362', '苗栗縣|頭屋鄉', 'Touwu Township, Miaoli County'),
    ('postal-code', 'zip_code3', '363', '苗栗縣|公館鄉', 'Gongguan Township, Miaoli County'),
    ('postal-code', 'zip_code3', '364', '苗栗縣|大湖鄉', 'Dahu Township, Miaoli County'),
    ('postal-code', 'zip_code3', '365', '苗栗縣|泰安鄉', 'Taian Township, Miaoli County'),
    ('postal-code', 'zip_code3', '366', '苗栗縣|銅鑼鄉', 'Tongluo Township, Miaoli County'),
    ('postal-code', 'zip_code3', '367', '苗栗縣|三義鄉', 'Sanyi Township, Miaoli County'),
    ('postal-code', 'zip_code3', '368', '苗栗縣|西湖鄉', 'Xihu Township, Miaoli County'),
    ('postal-code', 'zip_code3', '369', '苗栗縣|卓蘭鎮', 'Zhuolan Township, Miaoli County'),
    ('postal-code', 'zip_code3', '400', '臺中市|中區', 'Zhong Dist., Taichung City'),
    ('postal-code', 'zip_code3', '401', '臺中市|東區', 'Dong Dist., Taichung City'),
    ('postal-code', 'zip_code3', '402', '臺中市|南區', 'Nan Dist., Taichung City'),
    ('postal-code', 'zip_code3', '403', '臺中市|西區', 'Xi Dist., Taichung City'),
    ('postal-code', 'zip_code3', '404', '臺中市|北區', 'Bei Dist., Taichung City'),
    ('postal-code', 'zip_code3', '406', '臺中市|北屯區', 'Beitun Dist., Taichung City'),
    ('postal-code', 'zip_code3', '407', '臺中市|西屯區', 'Xitun Dist., Taichung City'),
    ('postal-code', 'zip_code3', '408', '臺中市|南屯區', 'Nantun Dist., Taichung City'),
    ('postal-code', 'zip_code3', '411', '臺中市|太平區', 'Taiping Dist., Taichung City'),
    ('postal-code', 'zip_code3', '412', '臺中市|大里區', 'Dali Dist., Taichung City'),
    ('postal-code', 'zip_code3', '413', '臺中市|霧峰區', 'Wufeng Dist., Taichung City'),
    ('postal-code', 'zip_code3', '414', '臺中市|烏日區', 'Wuri Dist., Taichung City'),
    ('postal-code', 'zip_code3', '420', '臺中市|豐原區', 'Fengyuan Dist., Taichung City'),
    ('postal-code', 'zip_code3', '421', '臺中市|后里區', 'Houli Dist., Taichung City'),
    ('postal-code', 'zip_code3', '422', '臺中市|石岡區', 'Shigang Dist., Taichung City'),
    ('postal-code', 'zip_code3', '423', '臺中市|東勢區', 'Dongshi Dist., Taichung City'),
    ('postal-code', 'zip_code3', '424', '臺中市|和平區', 'Heping Dist., Taichung City'),
    ('postal-code', 'zip_code3', '426', '臺中市|新社區', 'Xinshe Dist., Taichung City'),
    ('postal-code', 'zip_code3', '427', '臺中市|潭子區', 'Tanzi Dist., Taichung City'),
    ('postal-code', 'zip_code3', '428', '臺中市|大雅區', 'Daya Dist., Taichung City'),
    ('postal-code', 'zip_code3', '429', '臺中市|神岡區', 'Shengang Dist., Taichung City'),
    ('postal-code', 'zip_code3', '432', '臺中市|大肚區', 'Dadu Dist., Taichung City'),
    ('postal-code', 'zip_code3', '433', '臺中市|沙鹿區', 'Shalu Dist., Taichung City'),
    ('postal-code', 'zip_code3', '434', '臺中市|龍井區', 'Longjing Dist., Taichung City'),
    ('postal-code', 'zip_code3', '435', '臺中市|梧棲區', 'Wuqi Dist., Taichung City'),
    ('postal-code', 'zip_code3', '436', '臺中市|清水區', 'Qingshui Dist., Taichung City'),
    ('postal-code', 'zip_code3', '437', '臺中市|大甲區', 'Dajia Dist., Taichung City'),
    ('postal-code', 'zip_code3', '438', '臺中市|外埔區', 'Waibu Dist., Taichung City'),
    ('postal-code', 'zip_code3', '439', '臺中市|大安區', 'Daan Dist., Taichung City'),
    ('postal-code', 'zip_code3', '500', '彰化縣|彰化市', 'Zhanghua City, Changhua County'),
    ('postal-code', 'zip_code3', '502', '彰化縣|芬園鄉', 'Fenyuan Township, Changhua County'),
    ('postal-code', 'zip_code3', '503', '彰化縣|花壇鄉', 'Huatan Township, Changhua County'),
    ('postal-code', 'zip_code3', '504', '彰化縣|秀水鄉', 'Xiushui Township, Changhua County'),
    ('postal-code', 'zip_code3', '505', '彰化縣|鹿港鎮', 'Lugang Township, Changhua County'),
    ('postal-code', 'zip_code3', '506', '彰化縣|福興鄉', 'Fuxing Township, Changhua County'),
    ('postal-code', 'zip_code3', '507', '彰化縣|線西鄉', 'Xianxi Township, Changhua County'),
    ('postal-code', 'zip_code3', '508', '彰化縣|和美鎮', 'Hemei Township, Changhua County'),
    ('postal-code', 'zip_code3', '509', '彰化縣|伸港鄉', 'Shengang Township, Changhua County'),
    ('postal-code', 'zip_code3', '510', '彰化縣|員林市', 'Yuanlin City, Changhua County'),
    ('postal-code', 'zip_code3', '511', '彰化縣|社頭鄉', 'Shetou Township, Changhua County'),
    ('postal-code', 'zip_code3', '512', '彰化縣|永靖鄉', 'Yongjing Township, Changhua County'),
    ('postal-code', 'zip_code3', '513', '彰化縣|埔心鄉', 'Buxin Township, Changhua County'),
    ('postal-code', 'zip_code3', '514', '彰化縣|溪湖鎮', 'Xihu Township, Changhua County'),
    ('postal-code', 'zip_code3', '515', '彰化縣|大村鄉', 'Dacun Township, Changhua County'),
    ('postal-code', 'zip_code3', '516', '彰化縣|埔鹽鄉', 'Buyan Township, Changhua County'),
    ('postal-code', 'zip_code3', '520', '彰化縣|田中鎮', 'Tianzhong Township, Changhua County'),
    ('postal-code', 'zip_code3', '521', '彰化縣|北斗鎮', 'Beidou Township, Changhua County'),
    ('postal-code', 'zip_code3', '522', '彰化縣|田尾鄉', 'Tianwei Township, Changhua County'),
    ('postal-code', 'zip_code3', '523', '彰化縣|埤頭鄉', 'Pitou Township, Changhua County'),
    ('postal-code', 'zip_code3', '524', '彰化縣|溪州鄉', 'Xizhou Township, Changhua County'),
    ('postal-code', 'zip_code3', '525', '彰化縣|竹塘鄉', 'Zhutang Township, Changhua County'),
    ('postal-code', 'zip_code3', '526', '彰化縣|二林鎮', 'Erlin Township, Changhua County'),
    ('postal-code', 'zip_code3', '527', '彰化縣|大城鄉', 'Dacheng Township, Changhua County'),
    ('postal-code', 'zip_code3', '528', '彰化縣|芳苑鄉', 'Fangyuan Township, Changhua County'),
    ('postal-code', 'zip_code3', '530', '彰化縣|二水鄉', 'Ershui Township, Changhua County'),
    ('postal-code', 'zip_code3', '540', '南投縣|南投市', 'Nantou City, Nantou County'),
    ('postal-code', 'zip_code3', '541', '南投縣|中寮鄉', 'Zhongliao Township, Nantou County'),
    ('postal-code', 'zip_code3', '542', '南投縣|草屯鎮', 'Caotun Township, Nantou County'),
    ('postal-code', 'zip_code3', '544', '南投縣|國姓鄉', 'Guoxing Township, Nantou County'),
    ('postal-code', 'zip_code3', '545', '南投縣|埔里鎮', 'Buli Township, Nantou County'),
    ('postal-code', 'zip_code3', '546', '南投縣|仁愛鄉', 'Renai Township, Nantou County'),
    ('postal-code', 'zip_code3', '551', '南投縣|名間鄉', 'Mingjian Township, Nantou County'),
    ('postal-code', 'zip_code3', '552', '南投縣|集集鎮', 'Jiji Township, Nantou County'),
    ('postal-code', 'zip_code3', '553', '南投縣|水里鄉', 'Shuili Township, Nantou County'),
    ('postal-code', 'zip_code3', '555', '南投縣|魚池鄉', 'Yuchi Township, Nantou County'),
    ('postal-code', 'zip_code3', '556', '南投縣|信義鄉', 'Xinyi Township, Nantou County'),
    ('postal-code', 'zip_code3', '557', '南投縣|竹山鎮', 'Zhushan Township, Nantou County'),
    ('postal-code', 'zip_code3', '558', '南投縣|鹿谷鄉', 'Lugu Township, Nantou County'),
    ('postal-code', 'zip_code3', '600', '嘉義市|嘉義市', 'Chiayi City'),
    ('postal-code', 'zip_code3', '602', '嘉義縣|番路鄉', 'Fanlu Township, Chiayi County'),
    ('postal-code', 'zip_code3', '603', '嘉義縣|梅山鄉', 'Meishan Township, Chiayi County'),
    ('postal-code', 'zip_code3', '604', '嘉義縣|竹崎鄉', 'Zhuqi Township, Chiayi County'),
    ('postal-code', 'zip_code3', '605', '嘉義縣|阿里山鄉', 'Alishan Township, Chiayi County'),
    ('postal-code', 'zip_code3', '606', '嘉義縣|中埔鄉', 'Zhongbu Township, Chiayi County'),
    ('postal-code', 'zip_code3', '607', '嘉義縣|大埔鄉', 'Dabu Township, Chiayi County'),
    ('postal-code', 'zip_code3', '608', '嘉義縣|水上鄉', 'Shuishang Township, Chiayi County'),
    ('postal-code', 'zip_code3', '611', '嘉義縣|鹿草鄉', 'Lucao Township, Chiayi County'),
    ('postal-code', 'zip_code3', '612', '嘉義縣|太保市', 'Taibao City, Chiayi County'),
    ('postal-code', 'zip_code3', '613', '嘉義縣|朴子市', 'Puzi City, Chiayi County'),
    ('postal-code', 'zip_code3', '614', '嘉義縣|東石鄉', 'Dongshi Township, Chiayi County'),
    ('postal-code', 'zip_code3', '615', '嘉義縣|六腳鄉', 'Liujiao Township, Chiayi County'),
    ('postal-code', 'zip_code3', '616', '嘉義縣|新港鄉', 'Xingang Township, Chiayi County'),
    ('postal-code', 'zip_code3', '621', '嘉義縣|民雄鄉', 'Minxiong Township, Chiayi County'),
    ('postal-code', 'zip_code3', '622', '嘉義縣|大林鎮', 'Dalin Township, Chiayi County'),
    ('postal-code', 'zip_code3', '623', '嘉義縣|溪口鄉', 'Xikou Township, Chiayi County'),
    ('postal-code', 'zip_code3', '624', '嘉義縣|義竹鄉', 'Yizhu Township, Chiayi County'),
    ('postal-code', 'zip_code3', '625', '嘉義縣|布袋鎮', 'Budai Township, Chiayi County'),
    ('postal-code', 'zip_code3', '630', '雲林縣|斗南鎮', 'Dounan Township, Yunlin County'),
    ('postal-code', 'zip_code3', '631', '雲林縣|大埤鄉', 'Dapi Township, Yunlin County'),
    ('postal-code', 'zip_code3', '632', '雲林縣|虎尾鎮', 'Huwei Township, Yunlin County'),
    ('postal-code', 'zip_code3', '633', '雲林縣|土庫鎮', 'Tuku Township, Yunlin County'),
    ('postal-code', 'zip_code3', '634', '雲林縣|褒忠鄉', 'Baozhong Township, Yunlin County'),
    ('postal-code', 'zip_code3', '635', '雲林縣|東勢鄉', 'Dongshi Township, Yunlin County'),
    ('postal-code', 'zip_code3', '636', '雲林縣|臺西鄉', 'Taixi Township, Yunlin County'),
    ('postal-code', 'zip_code3', '637', '雲林縣|崙背鄉', 'Lunbei Township, Yunlin County'),
    ('postal-code', 'zip_code3', '638', '雲林縣|麥寮鄉', 'Mailiao Township, Yunlin County'),
    ('postal-code', 'zip_code3', '640', '雲林縣|斗六市', 'Douliu City, Yunlin County'),
    ('postal-code', 'zip_code3', '643', '雲林縣|林內鄉', 'Linnei Township, Yunlin County'),
    ('postal-code', 'zip_code3', '646', '雲林縣|古坑鄉', 'Gukeng Township, Yunlin County'),
    ('postal-code', 'zip_code3', '647', '雲林縣|莿桐鄉', 'Citong Township, Yunlin County'),
    ('postal-code', 'zip_code3', '648', '雲林縣|西螺鎮', 'Xiluo Township, Yunlin County'),
    ('postal-code', 'zip_code3', '649', '雲林縣|二崙鄉', 'Erlun Township, Yunlin County'),
    ('postal-code', 'zip_code3', '651', '雲林縣|北港鎮', 'Beigang Township, Yunlin County'),
    ('postal-code', 'zip_code3', '652', '雲林縣|水林鄉', 'Shuilin Township, Yunlin County'),
    ('postal-code', 'zip_code3', '653', '雲林縣|口湖鄉', 'Kouhu Township, Yunlin County'),
    ('postal-code', 'zip_code3', '654', '雲林縣|四湖鄉', 'Sihu Township, Yunlin County'),
    ('postal-code', 'zip_code3', '655', '雲林縣|元長鄉', 'Yuanzhang Township, Yunlin County'),
    ('postal-code', 'zip_code3', '700', '臺南市|中西區', 'Zhongxi Dist., Tainan City'),
    ('postal-code', 'zip_code3', '701', '臺南市|東區', 'Dong Dist., Tainan City'),
    ('postal-code', 'zip_code3', '702', '臺南市|南區', 'Nan Dist., Tainan City'),
    ('postal-code', 'zip_code3', '704', '臺南市|北區', 'Bei Dist., Tainan City'),
    ('postal-code', 'zip_code3', '708', '臺南市|安平區', 'Anping Dist., Tainan City'),
    ('postal-code', 'zip_code3', '709', '臺南市|安南區', 'Annan Dist., Tainan City'),
    ('postal-code', 'zip_code3', '710', '臺南市|永康區', 'Yongkang Dist., Tainan City'),
    ('postal-code', 'zip_code3', '711', '臺南市|歸仁區', 'Guiren Dist., Tainan City'),
    ('postal-code', 'zip_code3', '712', '臺南市|新化區', 'Xinhua Dist., Tainan City'),
    ('postal-code', 'zip_code3', '713', '臺南市|左鎮區', 'Zuozhen Dist., Tainan City'),
    ('postal-code', 'zip_code3', '714', '臺南市|玉井區', 'Yujing Dist., Tainan City'),
    ('postal-code', 'zip_code3', '715', '臺南市|楠西區', 'Nanxi Dist., Tainan City'),
    ('postal-code', 'zip_code3', '716', '臺南市|南化區', 'Nanhua Dist., Tainan City'),
    ('postal-code', 'zip_code3', '717', '臺南市|仁德區', 'Rende Dist., Tainan City'),
    ('postal-code', 'zip_code3', '718', '臺南市|關廟區', 'Guanmiao Dist., Tainan City'),
    ('postal-code', 'zip_code3', '719', '臺南市|龍崎區', 'Longqi Dist., Tainan City'),
    ('postal-code', 'zip_code3', '720', '臺南市|官田區', 'Guantian Dist., Tainan City'),
    ('postal-code', 'zip_code3', '721', '臺南市|麻豆區', 'Madou Dist., Tainan City'),
    ('postal-code', 'zip_code3', '722', '臺南市|佳里區', 'Jiali Dist., Tainan City'),
    ('postal-code', 'zip_code3', '723', '臺南市|西港區', 'Xigang Dist., Tainan City'),
    ('postal-code', 'zip_code3', '724', '臺南市|七股區', 'Qigu Dist., Tainan City'),
    ('postal-code', 'zip_code3', '725', '臺南市|將軍區', 'Jiangjun Dist., Tainan City'),
    ('postal-code', 'zip_code3', '726', '臺南市|學甲區', 'Xuejia Dist., Tainan City'),
    ('postal-code', 'zip_code3', '727', '臺南市|北門區', 'Beimen Dist., Tainan City'),
    ('postal-code', 'zip_code3', '730', '臺南市|新營區', 'Xinying Dist., Tainan City'),
    ('postal-code', 'zip_code3', '731', '臺南市|後壁區', 'Houbi Dist., Tainan City'),
    ('postal-code', 'zip_code3', '732', '臺南市|白河區', 'Baihe Dist., Tainan City'),
    ('postal-code', 'zip_code3', '733', '臺南市|東山區', 'Dongshan Dist., Tainan City'),
    ('postal-code', 'zip_code3', '734', '臺南市|六甲區', 'Liujia Dist., Tainan City'),
    ('postal-code', 'zip_code3', '735', '臺南市|下營區', 'Xiaying Dist., Tainan City'),
    ('postal-code', 'zip_code3', '736', '臺南市|柳營區', 'Liuying Dist., Tainan City'),
    ('postal-code', 'zip_code3', '737', '臺南市|鹽水區', 'Yanshui Dist., Tainan City'),
    ('postal-code', 'zip_code3', '741', '臺南市|善化區', 'Shanhua Dist., Tainan City'),
    ('postal-code', 'zip_code3', '742', '臺南市|大內區', 'Danei Dist., Tainan City'),
    ('postal-code', 'zip_code3', '743', '臺南市|山上區', 'Shanshang Dist., Tainan City'),
    ('postal-code', 'zip_code3', '744', '臺南市|新市區', 'Xinshi Dist., Tainan City'),
    ('postal-code', 'zip_code3', '745', '臺南市|安定區', 'Anding Dist., Tainan City'),
    ('postal-code', 'zip_code3', '800', '高雄市|新興區', 'Xinxing Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '801', '高雄市|前金區', 'Qianjin Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '802', '高雄市|苓雅區', 'Lingya Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '803', '高雄市|鹽埕區', 'Yancheng Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '804', '高雄市|鼓山區', 'Gushan Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '805', '高雄市|旗津區', 'Qijin Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '806', '高雄市|前鎮區', 'Qianzhen Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '807', '高雄市|三民區', 'Sanmin Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '811', '高雄市|楠梓區', 'Nanzi Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '812', '高雄市|小港區', 'Xiaogang Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '813', '高雄市|左營區', 'Zuoying Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '814', '高雄市|仁武區', 'Renwu Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '815', '高雄市|大社區', 'Dashe Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '817', '高雄市|東沙群島', 'Tungsha Islands, Kaohsiung City'),
    ('postal-code', 'zip_code3', '819', '高雄市|南沙群島', 'Nansha Islands, Kaohsiung City'),
    ('postal-code', 'zip_code3', '820', '高雄市|岡山區', 'Gangshan Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '821', '高雄市|路竹區', 'Luzhu Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '822', '高雄市|阿蓮區', 'Alian Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '823', '高雄市|田寮區', 'Tianliao Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '824', '高雄市|燕巢區', 'Yanchao Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '825', '高雄市|橋頭區', 'Qiaotou Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '826', '高雄市|梓官區', 'Ziguan Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '827', '高雄市|彌陀區', 'Mituo Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '828', '高雄市|永安區', 'Yongan Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '829', '高雄市|湖內區', 'Hunei Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '830', '高雄市|鳳山區', 'Fengshan Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '831', '高雄市|大寮區', 'Daliao Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '832', '高雄市|林園區', 'Linyuan Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '833', '高雄市|鳥松區', 'Niaosong Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '840', '高雄市|大樹區', 'Dashu Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '842', '高雄市|旗山區', 'Qishan Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '843', '高雄市|美濃區', 'Meinong Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '844', '高雄市|六龜區', 'Liugui Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '845', '高雄市|內門區', 'Neimen Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '846', '高雄市|杉林區', 'Shanlin Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '847', '高雄市|甲仙區', 'Jiaxian Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '848', '高雄市|桃源區', 'Taoyuan Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '849', '高雄市|那瑪夏區', 'Namaxia Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '851', '高雄市|茂林區', 'Maolin Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '852', '高雄市|茄萣區', 'Jiading Dist., Kaohsiung City'),
    ('postal-code', 'zip_code3', '880', '澎湖縣|馬公市', 'Magong City, Penghu County'),
    ('postal-code', 'zip_code3', '881', '澎湖縣|西嶼鄉', 'Xiyu Township, Penghu County'),
    ('postal-code', 'zip_code3', '882', '澎湖縣|望安鄉', 'Wangan Township, Penghu County'),
    ('postal-code', 'zip_code3', '883', '澎湖縣|七美鄉', 'Qimei Township, Penghu County'),
    ('postal-code', 'zip_code3', '884', '澎湖縣|白沙鄉', 'Baisha Township, Penghu County'),
    ('postal-code', 'zip_code3', '885', '澎湖縣|湖西鄉', 'Huxi Township, Penghu County'),
    ('postal-code', 'zip_code3', '890', '金門縣|金沙鎮', 'Jinsha Township, Kinmen County'),
    ('postal-code', 'zip_code3', '891', '金門縣|金湖鎮', 'Jinhu Township, Kinmen County'),
    ('postal-code', 'zip_code3', '892', '金門縣|金寧鄉', 'Jinning Township, Kinmen County'),
    ('postal-code', 'zip_code3', '893', '金門縣|金城鎮', 'Jincheng Township, Kinmen County'),
    ('postal-code', 'zip_code3', '894', '金門縣|烈嶼鄉', 'Lieyu Township, Kinmen County'),
    ('postal-code', 'zip_code3', '896', '金門縣|烏坵鄉', 'Wuqiu Township, Kinmen County'),
    ('postal-code', 'zip_code3', '900', '屏東縣|屏東市', 'Pingdong City, Pingtung County'),
    ('postal-code', 'zip_code3', '901', '屏東縣|三地門鄉', 'Sandemen Township, Pingtung County'),
    ('postal-code', 'zip_code3', '902', '屏東縣|霧臺鄉', 'Wutai Township, Pingtung County'),
    ('postal-code', 'zip_code3', '903', '屏東縣|瑪家鄉', 'Majia Township, Pingtung County'),
    ('postal-code', 'zip_code3', '904', '屏東縣|九如鄉', 'Jiuru Township, Pingtung County'),
    ('postal-code', 'zip_code3', '905', '屏東縣|里港鄉', 'Ligang Township, Pingtung County'),
    ('postal-code', 'zip_code3', '906', '屏東縣|高樹鄉', 'Gaoshu Township, Pingtung County'),
    ('postal-code', 'zip_code3', '907', '屏東縣|鹽埔鄉', 'Yanbu Township, Pingtung County'),
    ('postal-code', 'zip_code3', '908', '屏東縣|長治鄉', 'Zhangzhi Township, Pingtung County'),
    ('postal-code', 'zip_code3', '909', '屏東縣|麟洛鄉', 'Linluo Township, Pingtung County'),
    ('postal-code', 'zip_code3', '911', '屏東縣|竹田鄉', 'Zhutian Township, Pingtung County'),
    ('postal-code', 'zip_code3', '913', '屏東縣|萬丹鄉', 'Wandan Township, Pingtung County'),
    ('postal-code', 'zip_code3', '920', '屏東縣|潮州鎮', 'Chaozhou Township, Pingtung County'),
    ('postal-code', 'zip_code3', '921', '屏東縣|泰武鄉', 'Taiwu Township, Pingtung County'),
    ('postal-code', 'zip_code3', '922', '屏東縣|來義鄉', 'Laiyi Township, Pingtung County'),
    ('postal-code', 'zip_code3', '923', '屏東縣|萬巒鄉', 'Wanluan Township, Pingtung County'),
    ('postal-code', 'zip_code3', '924', '屏東縣|崁頂鄉', 'Kanding Township, Pingtung County'),
    ('postal-code', 'zip_code3', '925', '屏東縣|新埤鄉', 'Xinpi Township, Pingtung County'),
    ('postal-code', 'zip_code3', '926', '屏東縣|南州鄉', 'Nanzhou Township, Pingtung County'),
    ('postal-code', 'zip_code3', '927', '屏東縣|林邊鄉', 'Linbian Township, Pingtung County'),
    ('postal-code', 'zip_code3', '928', '屏東縣|東港鎮', 'Donggang Township, Pingtung County'),
    ('postal-code', 'zip_code3', '929', '屏東縣|琉球鄉', 'Liuqiu Township, Pingtung County'),
    ('postal-code', 'zip_code3', '931', '屏東縣|佳冬鄉', 'Jiadong Township, Pingtung County'),
    ('postal-code', 'zip_code3', '932', '屏東縣|新園鄉', 'Xinyuan Township, Pingtung County'),
    ('postal-code', 'zip_code3', '940', '屏東縣|枋寮鄉', 'Fangliao Township, Pingtung County'),
    ('postal-code', 'zip_code3', '941', '屏東縣|枋山鄉', 'Fangshan Township, Pingtung County'),
    ('postal-code', 'zip_code3', '942', '屏東縣|春日鄉', 'Chunri Township, Pingtung County'),
    ('postal-code', 'zip_code3', '943', '屏東縣|獅子鄉', 'Shizi Township, Pingtung County'),
    ('postal-code', 'zip_code3', '944', '屏東縣|車城鄉', 'Checheng Township, Pingtung County'),
    ('postal-code', 'zip_code3', '945', '屏東縣|牡丹鄉', 'Mudan Township, Pingtung County'),
    ('postal-code', 'zip_code3', '946', '屏東縣|恆春鎮', 'Hengchun Township, Pingtung County'),
    ('postal-code', 'zip_code3', '947', '屏東縣|滿州鄉', 'Manzhou Township, Pingtung County'),
    ('postal-code', 'zip_code3', '950', '臺東縣|臺東市', 'Taitung City, Taitung County'),
    ('postal-code', 'zip_code3', '951', '臺東縣|綠島鄉', 'Ludao Township, Taitung County'),
    ('postal-code', 'zip_code3', '952', '臺東縣|蘭嶼鄉', 'Lanyu Township, Taitung County'),
    ('postal-code', 'zip_code3', '953', '臺東縣|延平鄉', 'Yanping Township, Taitung County'),
    ('postal-code', 'zip_code3', '954', '臺東縣|卑南鄉', 'Beinan Township, Taitung County'),
    ('postal-code', 'zip_code3', '955', '臺東縣|鹿野鄉', 'Luye Township, Taitung County'),
    ('postal-code', 'zip_code3', '956', '臺東縣|關山鎮', 'Guanshan Township, Taitung County'),
    ('postal-code', 'zip_code3', '957', '臺東縣|海端鄉', 'Haiduan Township, Taitung County'),
    ('postal-code', 'zip_code3', '958', '臺東縣|池上鄉', 'Chishang Township, Taitung County'),
    ('postal-code', 'zip_code3', '959', '臺東縣|東河鄉', 'Donghe Township, Taitung County'),
    ('postal-code', 'zip_code3', '961', '臺東縣|成功鎮', 'Chenggong Township, Taitung County'),
    ('postal-code', 'zip_code3', '962', '臺東縣|長濱鄉', 'Zhangbin Township, Taitung County'),
    ('postal-code', 'zip_code3', '963', '臺東縣|太麻里鄉', 'Taimali Township, Taitung County'),
    ('postal-code', 'zip_code3', '964', '臺東縣|金峰鄉', 'Jinfeng Township, Taitung County'),
    ('postal-code', 'zip_code3', '965', '臺東縣|大武鄉', 'Dawu Township, Taitung County'),
    ('postal-code', 'zip_code3', '966', '臺東縣|達仁鄉', 'Daren Township, Taitung County'),
    ('postal-code', 'zip_code3', '970', '花蓮縣|花蓮市', 'Hualian City, Hualien County'),
    ('postal-code', 'zip_code3', '971', '花蓮縣|新城鄉', 'Xincheng Township, Hualien County'),
    ('postal-code', 'zip_code3', '972', '花蓮縣|秀林鄉', 'Xiulin Township, Hualien County'),
    ('postal-code', 'zip_code3', '973', '花蓮縣|吉安鄉', 'Jian Township, Hualien County'),
    ('postal-code', 'zip_code3', '974', '花蓮縣|壽豐鄉', 'Shoufeng Township, Hualien County'),
    ('postal-code', 'zip_code3', '975', '花蓮縣|鳳林鎮', 'Fenglin Township, Hualien County'),
    ('postal-code', 'zip_code3', '976', '花蓮縣|光復鄉', 'Guangfu Township, Hualien County'),
    ('postal-code', 'zip_code3', '977', '花蓮縣|豐濱鄉', 'Fengbin Township, Hualien County'),
    ('postal-code', 'zip_code3', '978', '花蓮縣|瑞穗鄉', 'Ruisui Township, Hualien County'),
    ('postal-code', 'zip_code3', '979', '花蓮縣|萬榮鄉', 'Wanrong Township, Hualien County'),
    ('postal-code', 'zip_code3', '981', '花蓮縣|玉里鎮', 'Yuli Township, Hualien County'),
    ('postal-code', 'zip_code3', '982', '花蓮縣|卓溪鄉', 'Zhuoxi Township, Hualien County'),
    ('postal-code', 'zip_code3', '983', '花蓮縣|富里鄉', 'Fuli Township, Hualien County')
ON DUPLICATE KEY UPDATE
    code_after = VALUES(code_after),
    code_description = VALUES(code_description);

INSERT INTO main_policy_master (policy_no, policy_seq, main_product_code, main_policy_years, insured_amount, premium)
VALUES ('P000000001', 1, 'LIFE', 20, 1000000.00, 15925.9089)
ON DUPLICATE KEY UPDATE
    main_product_code = VALUES(main_product_code),
    main_policy_years = VALUES(main_policy_years),
    insured_amount = VALUES(insured_amount),
    premium = VALUES(premium);

INSERT INTO main_policy_address (policy_no, policy_seq, address_type, zip_code3, zip_code2, full_width_address, half_width_address)
VALUES ('P000000001', 1, '01', '100', '001', '臺北市中正區重慶南路一段１號', 'No.1, Sec.1, Chongqing S. Rd., Zhongzheng Dist., Taipei City')
ON DUPLICATE KEY UPDATE
    zip_code3 = VALUES(zip_code3),
    zip_code2 = VALUES(zip_code2),
    full_width_address = VALUES(full_width_address),
    half_width_address = VALUES(half_width_address);

INSERT INTO main_policy_address (policy_no, policy_seq, address_type, zip_code3, zip_code2, full_width_address, half_width_address)
VALUES
    ('P000000001', 1, '02', '104', '001', '臺北市中山區南京東路二段１００號', 'No.100, Sec.2, Nanjing E. Rd., Zhongshan Dist., Taipei City'),
    ('P000000001', 1, '31', NULL, NULL, 'policyholder@example.com', 'policyholder@example.com')
ON DUPLICATE KEY UPDATE
    zip_code3 = VALUES(zip_code3),
    zip_code2 = VALUES(zip_code2),
    full_width_address = VALUES(full_width_address),
    half_width_address = VALUES(half_width_address);

INSERT INTO main_policy_ride (policy_no, policy_seq, ride_type, ride_order, product_code, policy_years, insured_amount, premium)
VALUES
    ('P000000001', 1, '1', '000', 'LIFE', 20, 1000000.00, 12345.6789),
    ('P000000001', 1, '2', '001', 'ADDR', 20, 500000.00, 2345.6700),
    ('P000000001', 1, '3', '002', 'FAMI', 20, 300000.00, 1234.5600)
ON DUPLICATE KEY UPDATE
    ride_type = VALUES(ride_type),
    product_code = VALUES(product_code),
    policy_years = VALUES(policy_years),
    insured_amount = VALUES(insured_amount),
    premium = VALUES(premium);

UPDATE main_policy_master master
SET premium = (
    SELECT COALESCE(SUM(ride.premium), 0)
    FROM main_policy_ride ride
    WHERE ride.policy_no = master.policy_no
      AND ride.policy_seq = master.policy_seq
)
WHERE policy_no = 'P000000001'
  AND policy_seq = 1;
