ALTER TABLE users
    ADD COLUMN created_by VARCHAR(128) NOT NULL DEFAULT 'system' AFTER enabled,
    ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER created_by,
    ADD COLUMN updated_by VARCHAR(128) NOT NULL DEFAULT 'system' AFTER created_at,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER updated_by;

ALTER TABLE authorities
    ADD COLUMN created_by VARCHAR(128) NOT NULL DEFAULT 'system' AFTER authority,
    ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER created_by,
    ADD COLUMN updated_by VARCHAR(128) NOT NULL DEFAULT 'system' AFTER created_at,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER updated_by;
